// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dashboard': string;
  'form': string;
  'reactForm': string;
}
declare var cssExports: CssExports;
export = cssExports;
