// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonWrapper': string;
  'header': string;
  'reactFinalForm': string;
  'section1': string;
  'section2': string;
}
declare var cssExports: CssExports;
export = cssExports;
